### ISSUE TITLE
Which model is really the best? 

### ISSUE THREAD

**Issue by ducha-aiki** [bluedream1121/self-sca-ori#3]
Hi,

There are several models available. 
Which model is the best? I am on the way of integrating your models into https://github.com/kornia/kornia and would like to make good general purpose defaults. 

Also, one more question - am I right that your evaluation on the IMC did not use scale/ori for descriptor calculation, but only for AdaLAM filtering?

**Comment by bluedream1121** [comment]
1. 

Hello, Dmytro.

To obtain the best model, you first run these scripts on your terminal:

cd trained_models
bash download_sca_model.sh
bash download_ori_model.sh


The best model for scale estimation is in the following directory:

trained_models/_0621_092607_resnet18_ori36_sca13_branchsca/best_model.pt


The best model for orientation estimation is in the following directory:

trained_models/_0213_121404_resnet18_ori36_sca13_branchori/best_model.pt




2. 

Yes, we don't use the scale and orientation for patch normalization (before the descriptor extraction stage) on the IMC dataset evaluation but only use the sca/ori in the AdaLAM filtering stage.

Thank you.

**Comment by ducha-aiki** [comment]
Thank you.

One more question - both models (scale and ori) also output other thing - ori and scale. So, what it is best _single_ model? :)

**Comment by bluedream1121** [comment]
Hello. Our proposed method is to train the scale and the orientation separately. We tried to train the joint model of scale/orientation, but the separately trained model performed better. 

For that reason, the scale best model and the orientation best model are provided separately.

**Comment by ducha-aiki** [comment]
Thank you. And finally - have you checked if the performance degrades on the grayscale images?

**Comment by bluedream1121** [comment]
No, I did not check the performance degrades on the grayscale images. 
Because we trained our model using RGB source image.
