### ISSUE TITLE
how to test on any two images?

### ISSUE THREAD

**Issue by kpbhat25** [bluedream1121/self-sca-ori#4]
How can run a demo or a test on any two images from which I want to extract keypoints?

**Comment by bluedream1121** [comment]
This model is used by the pipeline for extracting keypoints and obtaining the patch descriptors of those keypoints.
First, you use an external keypoint detector to get the keypoints, and when sampling the patch, use the test.py code to get the scale and orientation.
Then, extract the patch with the obtained keypoint (tx, ty) and scale, orientation (s, theta). When extracting the patch, you can use the laf_from_center_scale_ori function from the kornia library. (https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.laf_from_center_scale_ori)

This normalized patch is used as input to the patch descriptor extraction model.

Translated with www.DeepL.com/Translator (free version)

**Comment by bluedream1121** [comment]
This model is used by the pipeline for extracting keypoints and obtaining the patch descriptors of those keypoints.
First, you use an external keypoint detector to get the keypoints, and when sampling the patch, use the test.py code to get the scale and orientation.
Then, extract the patch with the obtained keypoint (tx, ty) and scale, orientation (s, theta). When extracting the patch, you can use the laf_from_center_scale_ori function from the kornia library. (https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.laf_from_center_scale_ori)

This normalized patch is used as input to the patch descriptor extraction model.
